"""add auth fields

Revision ID: f42c5b9e19c7
Revises: 26b77e2981a2
Create Date: 2026-03-04 14:41:00.103438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f42c5b9e19c7'
down_revision: Union[str, None] = '26b77e2981a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('CUSTOMER', 'INSTALLER', 'COOPERATIVE_ADMIN', 'SUPER_ADMIN', name='userrole'),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('CUSTOMER', 'INSTALLER', 'COOPERATIVE_ADMIN', 'SUPER_ADMIN', name='userrole'),
               existing_nullable=True)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
